In [ ]:
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
data=[range(1,5),range(5,9)]
d=np.array(data)

In [ ]:
d.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
a=np.array([0,1])

In [ ]:

a_col = a[:, np.newaxis]
print(a_col)
 

[[0]
 [1]]


In [ ]:
print(a_col.T)

[[0 1]]


In [ ]:
x=np.arange(2*3*4)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
x=x.reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
x[-1:,:,:]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
x[:,-2:,:]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
x[:,: ,::-1]

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])

In [ ]:
a=np.array([0,1])
b=np.array([2,3])
c=np.stack((a,b))
print(c)
d=np.stack((a,b)).T
print("Transpose:",d)
e=np.hstack((a[:,None],b[:,None]))
print("Horizontal ",e)
f=np.hstack((a,b))
print("Normal",f)
g=np.vstack((a,b))
print("vertical",g)

[[0 1]
 [2 3]]
Transpose: [[0 2]
 [1 3]]
Horizontal  [[0 2]
 [1 3]]
Normal [0 1 2 3]
vertical [[0 1]
 [2 3]]


In [ ]:
nums=np.arange(5)
print(nums)
print(nums*10)
print(np.sqrt(nums))
print(np.isnan(nums))
print(np.ceil(nums))
print(max(nums))

[0 1 2 3 4]
[ 0 10 20 30 40]
[0.         1.         1.41421356 1.73205081 2.        ]
[False False False False False]
[0. 1. 2. 3. 4.]
4


In [ ]:
v=np.random.randn(10)
w=np.random.randn(10)
dist=np.sqrt(np.sum((v-w)**2))
print(dist)

4.5694532005846895


In [ ]:
rnd=np.random.randn(4,2)
print(rnd)
rnd.mean()
rnd.std()
rnd.argmin()
rnd.sum()
print((rnd>0).sum())
print((rnd<0).sum())
print((rnd>0).all())

[[-0.61429162  1.81331067]
 [-0.76591479  3.11826034]
 [ 0.85362942  0.52820903]
 [-0.30004716 -0.76518805]]
4
4
False


In [ ]:
np.random.seed(1234)
np.random.rand(2,3)
np.random.randn(10)
np.random.randint(0,10,10)

array([2, 6, 3, 7, 0, 9, 0, 3, 2, 3])

In [ ]:
d=np.random.randn(4,2)
print(d)

[[-0.68282564 -0.94818614]
 [ 0.7773618   0.3251135 ]
 [-1.20348608  1.20954346]
 [ 0.15762162 -0.29355482]]


In [ ]:
np.min(d)

-1.2034860841764756

In [ ]:
np.where(d==np.min(d))

(array([2]), array([0]))

In [ ]:
np.argmin(d,axis=1)

array([1, 1, 0, 1])

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
columns=['name','age','gender','job']
user1=pd.DataFrame([['sahithi',20,'F','student'],
                    ['ramu',21,'M','student']],columns=columns)

In [ ]:
user2=pd.DataFrame([['Pathi',20,'M','student'],
                    ['Durga',21,'F','student']],columns=columns)
user3=pd.DataFrame([['Kishore',20,'M','scientist'],
                    ['krishna',21,'M','manager']],columns=columns)

In [ ]:
user4=pd.DataFrame(dict(name=['Nani','Depithi'],
                        age=[33,44],gender=['M','F'],
                        job=['engineer','scientist']))
print(user4)

      name  age gender        job
0     Nani   33      M   engineer
1  Depithi   44      F  scientist


In [ ]:
users=pd.concat([user1,user2,user3,user4])
users

name  age gender        job
0  sahithi   20      F    student
1     ramu   21      M    student
0    Pathi   20      M    student
1    Durga   21      F    student
0  Kishore   20      M  scientist
1  krishna   21      M    manager
0     Nani   33      M   engineer
1  Depithi   44      F  scientist

In [ ]:
user5=pd.DataFrame(dict(name=['sahithi','Pathi','Durga', 'Krishna','Nani','Depithi'],
                        height=[165,180,171,160,184,165]))
print(user5)

      name  height
0  sahithi     165
1    Pathi     180
2    Durga     171
3  Krishna     160
4     Nani     184
5  Depithi     165


In [ ]:
m=pd.merge(users,user5,on="name")
print(m)

      name  age gender        job  height
0  sahithi   20      F    student     165
1    Pathi   20      M    student     180
2    Durga   21      F    student     171
3     Nani   33      M   engineer     184
4  Depithi   44      F  scientist     165


In [ ]:
users=pd.merge(users,user5,on='name',how='outer')
print(users)

      name   age gender        job  height
0  sahithi  20.0      F    student   165.0
1     ramu  21.0      M    student     NaN
2    Pathi  20.0      M    student   180.0
3    Durga  21.0      F    student   171.0
4  Kishore  20.0      M  scientist     NaN
5  krishna  21.0      M    manager     NaN
6     Nani  33.0      M   engineer   184.0
7  Depithi  44.0      F  scientist   165.0
8  Krishna   NaN    NaN        NaN   160.0


In [ ]:
staked=pd.melt(users,id_vars='name',var_name='variable',value_name='value')
print(staked)

       name variable      value
0   sahithi      age       20.0
1      ramu      age       21.0
2     Pathi      age       20.0
3     Durga      age       21.0
4   Kishore      age       20.0
5   krishna      age       21.0
6      Nani      age       33.0
7   Depithi      age       44.0
8   Krishna      age        NaN
9   sahithi   gender          F
10     ramu   gender          M
11    Pathi   gender          M
12    Durga   gender          F
13  Kishore   gender          M
14  krishna   gender          M
15     Nani   gender          M
16  Depithi   gender          F
17  Krishna   gender        NaN
18  sahithi      job    student
19     ramu      job    student
20    Pathi      job    student
21    Durga      job    student
22  Kishore      job  scientist
23  krishna      job    manager
24     Nani      job   engineer
25  Depithi      job  scientist
26  Krishna      job        NaN
27  sahithi   height      165.0
28     ramu   height        NaN
29    Pathi   height      180.0
30    Du

In [ ]:
print(staked.pivot(index='name',columns='variable',values='value'))

variable   age gender height        job
name                                   
Depithi   44.0      F  165.0  scientist
Durga     21.0      F  171.0    student
Kishore   20.0      M    NaN  scientist
Krishna    NaN    NaN  160.0        NaN
Nani      33.0      M  184.0   engineer
Pathi     20.0      M  180.0    student
krishna   21.0      M    NaN    manager
ramu      21.0      M    NaN    student
sahithi   20.0      F  165.0    student


In [ ]:
users
type(users)

pandas.core.frame.DataFrame

In [ ]:
users.head()

name   age gender        job  height
0  sahithi  20.0      F    student   165.0
1     ramu  21.0      M    student     NaN
2    Pathi  20.0      M    student   180.0
3    Durga  21.0      F    student   171.0
4  Kishore  20.0      M  scientist     NaN

In [ ]:
users.tail()

name   age gender        job  height
4  Kishore  20.0      M  scientist     NaN
5  krishna  21.0      M    manager     NaN
6     Nani  33.0      M   engineer   184.0
7  Depithi  44.0      F  scientist   165.0
8  Krishna   NaN    NaN        NaN   160.0

In [ ]:
users.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [ ]:
users.columns

Index(['name', 'age', 'gender', 'job', 'height'], dtype='object')

In [ ]:
users.dtypes

name       object
age       float64
gender     object
job        object
height    float64
dtype: object

In [ ]:
users.shape

(9, 5)

In [ ]:
users.values

array([['sahithi', 20.0, 'F', 'student', 165.0],
       ['ramu', 21.0, 'M', 'student', nan],
       ['Pathi', 20.0, 'M', 'student', 180.0],
       ['Durga', 21.0, 'F', 'student', 171.0],
       ['Kishore', 20.0, 'M', 'scientist', nan],
       ['krishna', 21.0, 'M', 'manager', nan],
       ['Nani', 33.0, 'M', 'engineer', 184.0],
       ['Depithi', 44.0, 'F', 'scientist', 165.0],
       ['Krishna', nan, nan, nan, 160.0]], dtype=object)

In [ ]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    9 non-null      object 
 1   age     8 non-null      float64
 2   gender  8 non-null      object 
 3   job     8 non-null      object 
 4   height  6 non-null      float64
dtypes: float64(2), object(3)
memory usage: 432.0+ bytes


In [ ]:
users['gender']

0      F
1      M
2      M
3      F
4      M
5      M
6      M
7      F
8    NaN
Name: gender, dtype: object

In [ ]:
users.gender

0      F
1      M
2      M
3      F
4      M
5      M
6      M
7      F
8    NaN
Name: gender, dtype: object

In [ ]:
users[['age','gender']]

age gender
0  20.0      F
1  21.0      M
2  20.0      M
3  21.0      F
4  20.0      M
5  21.0      M
6  33.0      M
7  44.0      F
8   NaN    NaN

In [ ]:
df=users.copy()

In [ ]:
df.iloc[0]

name      sahithi
age          20.0
gender          F
job       student
height      165.0
Name: 0, dtype: object

In [ ]:
df.iloc[0,0]

'sahithi'

In [ ]:
for i in range(users.shape[0]):
  row=df.iloc[i]
  row.age*=100
print(df)

      name   age gender        job  height
0  sahithi  20.0      F    student   165.0
1     ramu  21.0      M    student     NaN
2    Pathi  20.0      M    student   180.0
3    Durga  21.0      F    student   171.0
4  Kishore  20.0      M  scientist     NaN
5  krishna  21.0      M    manager     NaN
6     Nani  33.0      M   engineer   184.0
7  Depithi  44.0      F  scientist   165.0
8  Krishna   NaN    NaN        NaN   160.0


/usr/local/lib/python3.8/dist-packages/pandas/core/series.py:1056: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()


In [ ]:
young=users.age<23

In [ ]:
young

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7    False
8    False
Name: age, dtype: bool

In [ ]:
df=users.copy()

In [ ]:
df.sort_values(by='age')

name   age gender        job  height
0  sahithi  20.0      F    student   165.0
2    Pathi  20.0      M    student   180.0
4  Kishore  20.0      M  scientist     NaN
1     ramu  21.0      M    student     NaN
3    Durga  21.0      F    student   171.0
5  krishna  21.0      M    manager     NaN
6     Nani  33.0      M   engineer   184.0
7  Depithi  44.0      F  scientist   165.0
8  Krishna   NaN    NaN        NaN   160.0

In [ ]:
df.sort_values(by=['age','job'])

name   age gender        job  height
4  Kishore  20.0      M  scientist     NaN
0  sahithi  20.0      F    student   165.0
2    Pathi  20.0      M    student   180.0
5  krishna  21.0      M    manager     NaN
1     ramu  21.0      M    student     NaN
3    Durga  21.0      F    student   171.0
6     Nani  33.0      M   engineer   184.0
7  Depithi  44.0      F  scientist   165.0
8  Krishna   NaN    NaN        NaN   160.0

In [ ]:
df.describe()

age      height
count   8.000000    6.000000
mean   25.000000  170.833333
std     8.847921    9.410986
min    20.000000  160.000000
25%    20.000000  165.000000
50%    21.000000  168.000000
75%    24.000000  177.750000
max    44.000000  184.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    9 non-null      object 
 1   age     8 non-null      float64
 2   gender  8 non-null      object 
 3   job     8 non-null      object 
 4   height  6 non-null      float64
dtypes: float64(2), object(3)
memory usage: 432.0+ bytes


In [ ]:
df.describe(include='all')

name        age gender      job      height
count         9   8.000000      8        8    6.000000
unique        9        NaN      2        4         NaN
top     sahithi        NaN      M  student         NaN
freq          1        NaN      5        4         NaN
mean        NaN  25.000000    NaN      NaN  170.833333
std         NaN   8.847921    NaN      NaN    9.410986
min         NaN  20.000000    NaN      NaN  160.000000
25%         NaN  20.000000    NaN      NaN  165.000000
50%         NaN  21.000000    NaN      NaN  168.000000
75%         NaN  24.000000    NaN      NaN  177.750000
max         NaN  44.000000    NaN      NaN  184.000000

In [ ]:
df.groupby('job')['age'].mean()

job
engineer     33.0
manager      21.0
scientist    32.0
student      20.5
Name: age, dtype: float64

In [ ]:
for grp,data in df.groupby('job'):
  print(grp,data)

engineer    name   age gender       job  height
6  Nani  33.0      M  engineer   184.0
manager       name   age gender      job  height
5  krishna  21.0      M  manager     NaN
scientist       name   age gender        job  height
4  Kishore  20.0      M  scientist     NaN
7  Depithi  44.0      F  scientist   165.0
student       name   age gender      job  height
0  sahithi  20.0      F  student   165.0
1     ramu  21.0      M  student     NaN
2    Pathi  20.0      M  student   180.0
3    Durga  21.0      F  student   171.0


In [ ]:
df.duplicated().sum()

0

In [ ]:
df.duplicated(['age','gender']).sum()

2

In [ ]:
df=df.drop_duplicates()

In [ ]:
df

name   age gender        job  height
0  sahithi  20.0      F    student   165.0
1     ramu  21.0      M    student     NaN
2    Pathi  20.0      M    student   180.0
3    Durga  21.0      F    student   171.0
4  Kishore  20.0      M  scientist     NaN
5  krishna  21.0      M    manager     NaN
6     Nani  33.0      M   engineer   184.0
7  Depithi  44.0      F  scientist   165.0
8  Krishna   NaN    NaN        NaN   160.0

In [ ]:
df.isnull().sum()

name      0
age       1
gender    1
job       1
height    3
dtype: int64

In [ ]:
df.height.isnull().sum()

3

In [ ]:
df.height.mean()

170.83333333333334

In [ ]:
df.dropna()

name   age gender        job  height
0  sahithi  20.0      F    student   165.0
2    Pathi  20.0      M    student   180.0
3    Durga  21.0      F    student   171.0
6     Nani  33.0      M   engineer   184.0
7  Depithi  44.0      F  scientist   165.0

In [ ]:
df.loc[df.height.isnull(),'height']=df['height'].mean()

In [ ]:
df

name   age gender        job      height
0  sahithi  20.0      F    student  165.000000
1     ramu  21.0      M    student  170.833333
2    Pathi  20.0      M    student  180.000000
3    Durga  21.0      F    student  171.000000
4  Kishore  20.0      M  scientist  170.833333
5  krishna  21.0      M    manager  170.833333
6     Nani  33.0      M   engineer  184.000000
7  Depithi  44.0      F  scientist  165.000000
8  Krishna   NaN    NaN        NaN  160.000000

In [ ]:
df.age.mean()

25.0

In [ ]:
df.loc[df.age.isnull(),'age']=df.age.mean()

In [ ]:
df

name   age gender        job      height
0  sahithi  20.0      F    student  165.000000
1     ramu  21.0      M    student  170.833333
2    Pathi  20.0      M    student  180.000000
3    Durga  21.0      F    student  171.000000
4  Kishore  20.0      M  scientist  170.833333
5  krishna  21.0      M    manager  170.833333
6     Nani  33.0      M   engineer  184.000000
7  Depithi  44.0      F  scientist  165.000000
8  Krishna  25.0    NaN        NaN  160.000000

In [ ]:
df.gender.mode()
 

0    M
dtype: object

In [ ]:
df.loc[df.gender.isnull(),'gender']=df.gender.mode()
 

In [ ]:
df

name   age gender        job      height
0  sahithi  20.0      F    student  165.000000
1     ramu  21.0      M    student  170.833333
2    Pathi  20.0      M    student  180.000000
3    Durga  21.0      F    student  171.000000
4  Kishore  20.0      M  scientist  170.833333
5  krishna  21.0      M    manager  170.833333
6     Nani  33.0      M   engineer  184.000000
7  Depithi  44.0      F  scientist  165.000000
8  Krishna  25.0    NaN        NaN  160.000000

In [ ]:
df.job.mode()

0    student
dtype: object

In [ ]:
df.loc[df.job.isnull(),'job']=df.job.mode()

In [ ]:
df

name   age gender        job      height
0  sahithi  20.0      F    student  165.000000
1     ramu  21.0      M    student  170.833333
2    Pathi  20.0      M    student  180.000000
3    Durga  21.0      F    student  171.000000
4  Kishore  20.0      M  scientist  170.833333
5  krishna  21.0      M    manager  170.833333
6     Nani  33.0      M   engineer  184.000000
7  Depithi  44.0      F  scientist  165.000000
8  Krishna  25.0    NaN        NaN  160.000000

In [ ]:
df.columns

Index(['name', 'age', 'gender', 'job', 'height'], dtype='object')

In [ ]:
size =pd.Series(np.random.normal(loc=175,size=20,scale=10))

In [ ]:
size[:3]+=300

In [ ]:
size

0     487.399232
1     473.960274
2     482.545638
3     169.658187
4     175.469696
5     185.231051
6     162.034310
7     174.816123
8     174.357213
9     184.025422
10    181.195632
11    178.080818
12    189.593667
13    178.921104
14    158.998939
15    159.156120
16    170.613498
17    178.068871
18    185.210459
19    170.324236
dtype: float64

In [ ]:
size_outlr=size.copy()

In [ ]:
size_outlr[((size-size.mean()).abs() > 3*size.std())]=size.mean()

In [ ]:
size_outlr.mean()

220.98302446935986

In [ ]:
mad = 1.4826 * np.median(np.abs(size - size.median()))
size_outlr_mad = size.copy()
size_outlr_mad[((size - size.median()).abs() > 3 * mad)] = size.median()
print(size_outlr_mad.mean(), size_outlr_mad.median())

175.49899392423794 178.07185762434986


In [ ]:
import tempfile,os.path

In [ ]:
tmpdir=tempfile.gettempdir()

In [ ]:
csv_file=os.path.join(tmpdir,'users.csv')

In [ ]:
import sqlite3

In [ ]:
db_file=os.path.join(tmpdir,'users.db')

In [ ]:
conn=sqlite3.connect(db_file)

In [ ]:
url = 'https://raw.github.com/neurospin/pystatsml/master/datasets/salary_table.csv'
salary = pd.read_csv(url)
salary.to_sql("salary", conn, if_exists="replace")

/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py:2872: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  sql.to_sql(


In [ ]:
cur=conn.cursor()
values=(100,1400,)
cur.execute("insert into salary values (?, ?)", values)
conn.commit()

Exercise

In [ ]:
path='https://github.com/neurospin/pystatsml/blob/master/datasets/iris.csv'
data=pd.read_csv(path)

ParserError: ignored